### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by thibmaek** [albinekb/hyperclean#1]
You might want to update the description since in hpm it now shows the generic message of "Hyperterm plugin"

**Comment by albinekb** [comment]
Thanks @thibmaek, will do as soon as possible 👍  

Would you like me to invite you to this repo? I'm currently focused on fixing bugs in hyperterm, so not really having time to update this plugin, (adding https://github.com/albinekb/hyperclean/commit/c596719ee22593f849bd76295a4a835a62a0220a#commitcomment-18417201 for example)

Let me know 🙌

**Comment by thibmaek** [comment]
I think a simple PR should suffice for this? I'll get to it ;)

**Comment by albinekb** [comment]
Closed in #2 and I'll release a new version
