### ISSUE TITLE
Hyper 1.0 support

### ISSUE THREAD

**Issue by rastasheep** [albinekb/hyperclean#6]
It seems that there was some markup/elektron changes in newest Hyper version, which causes window actions to be visible again.
![screen shot 2016-12-13 at 8 15 39 pm](https://cloud.githubusercontent.com/assets/695790/21155163/466a2348-c171-11e6-894f-4caf3d3d5ffd.png)

**Comment by albinekb** [comment]
PR welcome, If not, i have time to fix this during the weekend.

Thanks for the issue @rastasheep 🎉
